title: Texas2036 Indicators
description: View Updated Indicators for the Texas 2036 Strategic Framework

markup:
  goldmark:
    renderer:
      unsafe:           true
  highlight:
    noClasses:          false
  tableOfContents:
    startLevel:         2
    endLevel:           6